### ISSUE TITLE
Undefined variable: crud (View: /home/nisteanunturi/public_html/vendor/backpack/langfilemanager/src/resources/views/translations.blade.php)

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/langfilemanager#13]
When i access /admin/language/texts i get the error in the title, and when i access /admin/language i get "FatalErrorException in Crud.php line 195: Call to a member function get() on null". Usually the function getEntries gets an object as $this->crud->query but this is null when accessing the language section.

[laravel-2016-06-06.txt](https://github.com/Laravel-Backpack/langfilemanager/files/300167/laravel-2016-06-06.txt)

**Comment by f-liva** [comment]
The same here

**Comment by Alf3001** [comment]
+1

**Comment by bulukcrazy** [comment]
some trouble

**Comment by Ghitu** [comment]
Please update the package with composer. It should fix the issue.

**Comment by AurelDragut** [comment]
Yeah, it's working now. Great job, mate!
