### ISSUE TITLE
error add language

### ISSUE THREAD

**Issue by guillermohaad** [Laravel-Backpack/langfilemanager#21]
hi friend @tabacitu 

I try to add a new language and to save I get this error?
atached image:

![error_language](https://cloud.githubusercontent.com/assets/12921805/18439747/1cda7d5e-78cc-11e6-8a7f-7d57855ec538.png)
![error_language2](https://cloud.githubusercontent.com/assets/12921805/18439758/22048130-78cc-11e6-9027-19f1fa1bd022.png)

**Comment by tabacitu** [comment]
@Ghitu ? Maybe the LanguageCrudController no longer works with Laravel 5.3 because MySQL strict is ON by default?

**Comment by guillermohaad** [comment]
@tabacitu I put a strict MySQL off and follows the problem, thank you

**Comment by tabacitu** [comment]
Hmm... what if you set write permissions on your `/resources/lang` and its subdirectories?

**Comment by Ghitu** [comment]
@guillermohaad Check to see if you have selected a default language. You must have a default language selected.

**Comment by guillermohaad** [comment]
Good morning, @Ghitu voy a check , thank you

**Comment by lloy0076** [comment]
If this is still an issue, please reopen.
