### ISSUE TITLE
Undefined index: 2015_09_10_124414_alter_languages_table

### ISSUE THREAD

**Issue by youngerrainbow** [Laravel-Backpack/langfilemanager#25]
php artisan migrate:refresh    will show  error **Undefined index: 2015_09_10_124414_alter_languages_table**

**Comment by youngerrainbow** [comment]
`$this->loadMigrationsFrom(realpath(__DIR__.'/database/migrations'), 'langfilemanager');`
    **i fix this add above code to serviceprovider**

**Comment by tabacitu** [comment]
That's a good fix, thanks.

But I think a better solution would be to NOT instruct people to run the migrations directly from the package, but allow (and instruct) them to publish the migration, then run `php artisan migrate`. This would prevent the problem above AND would also make sure developers commit the migration to their repository and push it to their test/production env.

@Ghitu , right?

**Comment by Ghitu** [comment]
@tabacitu I agree

**Comment by WanderingKazuma** [comment]
I'm currently seeing this issue, but I'm a little confused as to where I would add @youngerrainbow 's fix.

**Comment by lloy0076** [comment]
@Ghitu @tabacitu  What is the fix here?

**Comment by lloy0076** [comment]
In the absence of a fix (and no-one complaining) I'm closing this.
