### ISSUE TITLE
General error: 1364 Field 'app_name' doesn't have a default value 

### ISSUE THREAD

**Issue by techtichub** [Laravel-Backpack/langfilemanager#26]
When creating a new language, it is showing default value error for column 'app_name'

![screenshot_1](https://cloud.githubusercontent.com/assets/9209924/19956489/5e771fb4-a1b3-11e6-80a6-2ebc320e8729.png)
we should add default value for 'app_name' column

**Comment by tabacitu** [comment]
@Ghitu ? any ideas?

**Comment by Ghitu** [comment]
@techtichub @tabacitu just remove the filed from table. It is not used. I've updated the migration and seed.

**Comment by ghost** [comment]
Add this field to the $fillable array in your model.

**Comment by aguywithnojob** [comment]
you should go to your model file and add $fillable array in it for this column too...
