### ISSUE TITLE
Possibility to change table name

### ISSUE THREAD

**Issue by gmatkowski** [Laravel-Backpack/langfilemanager#27]
I guess you should implement method to change table name ... "languages" is to common and can already exists in database structure ... like in my case ;-)

**Comment by yangranger** [comment]
+1

**Comment by yangranger** [comment]
for my case, make my own migration without creating table but adding missing colums, works.

**Comment by lloy0076** [comment]
Whilst I agree this should be done, no-one has made a PR - please reopen when a PR is available.
