### ISSUE TITLE
Saved file should be formatted to coding standard

### ISSUE THREAD

**Issue by odinns** [Laravel-Backpack/langfilemanager#28]
The language files saved by LangFileManager has these styling problems:

1. The return statement is indented by one space. Should be no space.
2. The strings are enclosed with "double quotes", should be 'single quotes'.
3. The array of elements must have the last element also with a trailing comma. 
4. The file is missing a final newline.

**Comment by yusufkandemir** [comment]
I was working on it, it is almost done. I read contributing guidelines a bit late. I will publish a PR soon.

**Comment by tabacitu** [comment]
Thanks a lot @odinns & @yusufkandemir - it's finally fixed by merging @yusufkandemir 's PR #64 . Sorry for taking so long to take care of this - must have slipped through the cracks. See my mentions at the bottom of #64 please.

Cheers!
