### ISSUE TITLE
QueryException 1364 Field 'app_name' doesn't gave a default value

### ISSUE THREAD

**Issue by debock1984** [Laravel-Backpack/langfilemanager#36]
Hello

Did a fresh install of laravel 5.4 and backpack. (everything going fine)
Did the [3 steps](https://github.com/Laravel-Backpack/LangFileManager) of the langFileManager.

When adding a new language i get the following error (missing field value)

![image](https://cloud.githubusercontent.com/assets/24493602/26700095/671fa15e-471c-11e7-950b-ed1f9a9df69b.png)

![image](https://cloud.githubusercontent.com/assets/24493602/26700107/6d6e7792-471c-11e7-863c-68496ff3d0a8.png)

The folder itself is of course created as expected, although its not created with group write permissions, but i guess that has nothing to do with laravel/backpack, and has no influence on the above issue i think.

![image](https://cloud.githubusercontent.com/assets/24493602/26700211/dbd1088a-471c-11e7-8a92-b7301a4ed7dc.png)

Database table:

![image](https://cloud.githubusercontent.com/assets/24493602/26700266/0dc85212-471d-11e7-9f77-839a48201d50.png)

**Comment by debock1984** [comment]
OK just noticed that the field "app_name" was removed in [this commit](https://github.com/Laravel-Backpack/LangFileManager/commit/49698e22d046242e03ba797f9e56ddd86b588ffc)

So i just deleted it from the database and all is fine.
So seems that the migration in the step 3 was still adding it.

**Comment by tabacitu** [comment]
Yes, looks like @AlinGhitu removed that column by modifying the migration, instead of creating a new migration to remove the column - that's what created the breaking change. 

Sorry for that. Removing the column manually should fix it for everyone who installed it before this change.

Cheers!
