### ISSUE TITLE
Adding new Language error

### ISSUE THREAD

**Issue by vanvanni** [Laravel-Backpack/langfilemanager#41]
When attempted to add new language: `SQLSTATE[HY000]: General error: 1364 Field 'app_name' doesn't have a default value (SQL: insert into `languages` (`name`, `native`, `abbr`, `flag`, `active`, `default`) values (Dutch, Dutch, nl, , 1, 1))`

**Comment by debock1984** [comment]
duplicate of https://github.com/Laravel-Backpack/LangFileManager/issues/36 ?

**Comment by tabacitu** [comment]
Yes. Please remove the app_name column from your DB manually. That should fix it.

**Comment by lloy0076** [comment]
This is a duplicate - it should be closed :(
