### ISSUE TITLE
Extend the routes functionality

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/langfilemanager#42]
Seems like this package does not allow you to extend the routes by just placing a route file in ```routes/backpack/langfilemanager.php```. It should :-) 

Consistent behaviour FTW!

**Comment by lloy0076** [comment]
@tabacitu - what's up with this?

**Comment by jakobjohansson** [comment]
Any progress on this?

**Comment by tabacitu** [comment]
Thank you @gpibarra and @jakobjohansson . Just merged your PRs that introduce this functionality. After a ```composer update``` you can use a custom routes file.

Cheers!
