### ISSUE TITLE
Scandir exception when switching languages and no dir exists.

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/langfilemanager#45]
We should handle this with a warning in the UI and not die hard with a full exception.

Or even better, do not show the language in the switcher if the language dir does not exist or create it on the fly and display an empty page -> should suggest to the developer that lang files are missing not scare him.

Screen:
![image](https://user-images.githubusercontent.com/1476365/30006178-576b568a-90fb-11e7-81bd-3f44784cdc3a.png)

Video:
https://www.useloom.com/share/d9840aeb837245c2a68c35d8ce3137ee

**Comment by lloy0076** [comment]
I agree (PRs are welcome!) - and I think it's actually a bug.

**Comment by tabacitu** [comment]
@lucianobapo has already submitted a PR for this, just merged it. Cheers, thank you!
