### ISSUE TITLE
Package migrations and seeds should be publishable

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/langfilemanager#46]
When developing and using, for example, something like `php artisan migrate:refresh --seed` the migrations and seeds for languages are not getting migrated again.

This results in an inconsistent development flow and database artifact tables.

Output errors because of missing migrations example:
```
$ php artisan migrate:refresh --seed
Migration not found: 2015_09_10_124414_alter_languages_table
Migration not found: 2015_09_07_190535_create_languages_table
Rolling back: 2014_10_12_100000_create_password_resets_table
Rolled back:  2014_10_12_100000_create_password_resets_table
Rolling back: 2014_10_12_000000_create_users_table
Rolled back:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Seeding: UsersTableSeeder
User seeding successful.
```

**Comment by iMokhles** [comment]
agree with this i thought the same i had to do it manually but today i released that it will be easy if the files were publish

**Comment by lloy0076** [comment]
PRs are welcome but this seems to be both an enhancement and a bug.

**Comment by tabacitu** [comment]
Hi guys, the docs now instruct us to publish the migration files, so that this would no longer be an issue.

Thanks, cheers!

**Comment by o15a3d4l11s2** [comment]
Is there something more that has to be done? I have followed the guide, but the seed and migration are never published.
