### ISSUE TITLE
405 method not allowed on POST search request in language list

### ISSUE THREAD

**Issue by gabriel-cardoso** [Laravel-Backpack/langfilemanager#49]
# Bug report

405 error on POST request on `admin/language/search` request used by AJAX table

### What I did:

Installed LangFileManager and tried to access the `admin/language` page

### What I expected to happen:

See a list of available languages

### What happened:

JS alert notifying and error.

### What I've already tried to fix it:

Changing this line https://github.com/Laravel-Backpack/LangFileManager/blob/master/src/app/Http/routes.php#L8
with 
`CRUD::resource('language', 'LanguageCrudController');`

### Backpack, Laravel, PHP, DB version:

Backpack v0.8.2
Laravel v5.5.20
PHP 7.10.1
DB Mysql

**Comment by gabriel-cardoso** [comment]
Made a PR https://github.com/Laravel-Backpack/LangFileManager/pull/50
Let me know if I missed something here, kind of new to Laravel and Backpack...
Thanks !

**Comment by tabacitu** [comment]
Hi @gabriel-cardoso ,

The PR is perfect, thank you. Very good job!

Cheers!
