### ISSUE TITLE
Language Route admin/language Access Error on Laravel 5.5

### ISSUE THREAD

**Issue by lucianobapo** [Laravel-Backpack/langfilemanager#53]
# Bug report

### What I did:
When access route admin/language

### What I expected to happen:
Expected to open list of languages

### What happened:
DataTables warning: table id=crudTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### What I've already tried to fix it:
Tried and fixed it!

Change on app/Http/routes.php file
From: "Route::resource('language', 'LanguageCrudController');"
To:  "CRUD::resource('language', 'LanguageCrudController');"
It works like a charm!

### Backpack, Laravel, PHP, DB version: 
backpack/langfilemanager "version": "1.0.21",

"name": "laravel/framework","version": "v5.5.21",

PHP v7.1
DB: Postgresql

**Comment by lucianobapo** [comment]
#50 here is the solution

**Comment by nicolabavaro** [comment]
Thanks! @lucianobapo

**Comment by tabacitu** [comment]
Merged! Thanks @lucianobapo and @nicolabavaro .
