### ISSUE TITLE
Do you accept PR for unit tests ?

### ISSUE THREAD

**Issue by abdelrahmanahmed** [Laravel-Backpack/langfilemanager#56]
I want to help you with unit tests for this awesome package , is it ok for you? . If yes , is there any guidelines that i should follow when writing unit tests for this package ?

**Comment by lloy0076** [comment]
See the various tests [here](https://github.com/Laravel-Backpack/CRUD/tree/master/tests/Unit/CrudPanel) for examples in the "sister" CRUD project.

All PRs are welcome.

**Comment by tabacitu** [comment]
Yes please! :-)

**Comment by promatik** [comment]
Once again, PRs are super welcome 🙌
I'm going to close this issue for now.
