### ISSUE TITLE
difficult to publish Backpack\LangFileManager

### ISSUE THREAD

**Issue by mandahylla** [Laravel-Backpack/langfilemanager#60]
# Bug report
Hi @tabacitu, 
I install Laravel-Backpack/LangFileManager on laravel 5.4

i want to install and publish language table cause at register view the display is not awesome

but after publishing for migrate, the "php artisan migrate" gave "nothing to migrate" and "php artisan db:seed --class="Backpack\LangFileManager\database\seeds\LanguageTableSeeder" " gave an error on database.

how can i fix this ? 

Backpack 0.7.1, Laravel5.4, PHP5.6, DB version:mysql5.7.19 on windows 10 with wampserver3.1

**Comment by mandahylla** [comment]
just want to know if backpack can work correctly on laravel 5.4 or do i need to up to php7 and laravel5.6

**Comment by promatik** [comment]
Hi @mandahylla!
Sorry for not providing an answer in time for this one 🤦‍♂️

I'm going to close it since it's probably not an issue anymore, I just tested this package today and it's working fine.
