### ISSUE TITLE
How unistall  ?

### ISSUE THREAD

**Issue by a21ns1g4ts** [Laravel-Backpack/langfilemanager#62]
## Ask:
 How to remove all files generated by LangFileManager ?

**Comment by tabacitu** [comment]
Hi @Atiladanvi ,

Unfortunately, this package does not have an "uninstall" procedure. In fact, I think most (if not all) Composer packages lack this.

You should be able to uninstall the package manually by:
1. Running ```composer remove backpack/langfilemanager```.
2. Removing the migrations, seeds, config and lang files that were published when you installed the package.
3. Remove the menu item from your sidebar.

Sorry I couldn't be of more help.

Cheers!
