### ISSUE TITLE
Old filecontents are shown

### ISSUE THREAD

**Issue by Suven** [Laravel-Backpack/langfilemanager#68]
# Bug report
Hey,

with recent installations I have the problem that, after the user saves a new translation, the inputs are filled with the old translation-values. The file however, is correctly persisted with the new strings. When hitting refresh in the browser, the new values are being displayed.

### Backpack, Laravel, PHP, DB version:

- Backpack Base: 0.9.6
- Backpack LangFileManager: 1.0.25
- Laravel Framework 5.6.27
- PHP 7.2.11

**Comment by promatik** [comment]
Hi @Suven, I use this package for a long time and this has never happen to me, since this issue is also super old I'm going to close it for now. Anyway, if anyone thinks this is still an issue please re-open 🙌
