### ISSUE TITLE
403,  Forbidden. This action is unauthorized.

### ISSUE THREAD

**Issue by Dontorpedo** [Laravel-Backpack/langfilemanager#70]
# Bug report

### What I did:
fresh insallation 
### What I expected to happen:
activating the language
### What happened:
403 error, action unauthorized

### Backpack, Laravel, PHP, DB version:

latest backpack, laravel, 5.7

**Comment by higoglhf** [comment]
Hello! Backpack\LangFileManager\app\Http\Requests\LanguageRequest authorize method must be `public function authorize()
    {
        return backpack_auth()->check();
    }` 
instead of  `public function authorize()
    {
        return \Auth::check();
    }`

**Comment by Dontorpedo** [comment]
thank you very mutch! it works now
