### ISSUE TITLE
Trying to get property of non-object from the Blade

### ISSUE THREAD

**Issue by eheitman** [Laravel-Backpack/langfilemanager#75]
# Bug report

(3/3) ErrorExceptionTrying to get property of non-object (View: /server/html/pricetool/resources/views/products/partials/table.blade.php) (View: /server/html/pricetool/resources/views/products/partials/table.blade.php)
--

###My Blade code "I am not Sure What is the issue"

@if (! is_null($products))
<table class="table table-striped table-bordered table-hover data-table overview">
    <thead>
        <tr>
            <th data-col="sku">SKU</th>
            <th data-col="name">Name</th>
            <th width="230" data-col="vendor">Vendor</th>
            <th data-col="part_number">Part Number</th>
            <th data-col="description">Description</th>
            <th width="115" data-col="lastupdate">Last Update</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($products as $product)
        <tr data-url="{{ route('products.show', [$product->id]) }}">
            <td>{{ $product->sku->code ?: "" }}</td>
            <td>{{ $product->name }}</td>
            <td>{{ $product->vendor->name ?: "" }}</td>
            <td>{{ $product->part_number }}</td>
            <td>{{ $product->description }}</td>
            <td>{{ $product->updated_at }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

**Comment by johnpuddephatt** [comment]
I'm not sure this problem is specific to Laravel Backpack in any way?

Try doing `dd($products)` before your `@foreach`... I suspect the problem is that your collection is empty, and that instead of doing `@if(! is_null($products))` you want to be doing `@if(! empty($products))`

**Comment by eheitman** [comment]
Thanks For your reply, could you check my route please..

<?php

Route::get('/', function () {
    return redirect()->route('quotes.index');
});

Route::get('/quotes', ['as' => 'quotes.index', 'uses' => 'QuotesController@index']);
Route::post('/quotes', ['as' => 'quotes.calculate', 'uses' => 'QuotesController@calculate']);
Route::post('/quotes/all', ['as' => 'quotes.allPrices', 'uses' => 'QuotesController@allPrices']);
Route::post('/quotes/email', ['as' => 'quotes.email', 'uses' => 'QuotesController@sendEmail']);

Route::get('/products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
Route::get('/products/local', ['as' => 'products.local', 'uses' => 'ProductsController@local']);
Route::get('/products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
Route::post('/products', ['as' => 'products.store', 'uses' => 'ProductsController@store']);
Route::get('/products/{product}', ['as' => 'products.show', 'uses' => 'ProductsController@show']);
Route::post('/products/{product}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
Route::delete('/products/{product}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);

Route::get('/products/{product}/duplicate', ['as' => 'products.duplicate', 'uses' => 'ProductsController@duplicate']);
Route::get('/products/{product}/shipping', ['as' => 'products.shipping', 'uses' => 'ProductsController@shipping']);

Route::get('/skus', ['as' => 'skus.index', 'uses' => 'SkusController@index']);
Route::get('/skus/create', ['as' => 'skus.create', 'uses' => 'SkusController@create']);
Route::get('/skus/{sku}', ['as' => 'skus.show', 'uses' => 'SkusController@show']);
Route::post('/skus', ['as' => 'skus.store', 'uses' => 'SkusController@store']);
Route::post('/skus/{sku}', ['as' => 'skus.update', 'uses' => 'SkusController@update']);
Route::delete('/skus/{sku}', ['as' => 'skus.destroy', 'uses' => 'SkusController@destroy']);

Route::get('/pricelevels', ['as' => 'pricelevels.index', 'uses' => 'PriceLevelsController@index']);
Route::get('/pricelevels/create', ['as' => 'pricelevels.create', 'uses' => 'PriceLevelsController@create']);
Route::get('/pricelevels/{priceLevel}', ['as' => 'pricelevels.show', 'uses' => 'PriceLevelsController@show']);
Route::post('/pricelevels', ['as' => 'pricelevels.store', 'uses' => 'PriceLevelsController@store']);
Route::post('/pricelevels/{priceLevel}', ['as' => 'pricelevels.update', 'uses' => 'PriceLevelsController@update']);
Route::delete('/pricelevels/{priceLevel}', ['as' => 'pricelevels.destroy', 'uses' => 'PriceLevelsController@destroy']);

Route::get('/vendors', ['as' => 'vendors.index', 'uses' => 'VendorsController@index']);
Route::get('/vendors/create', ['as' => 'vendors.create', 'uses' => 'VendorsController@create']);
Route::get('/vendors/{vendor}', ['as' => 'vendors.show', 'uses' => 'VendorsController@show']);
Route::post('/vendors', ['as' => 'vendors.store', 'uses' => 'VendorsController@store']);
Route::post('/vendors/{vendor}', ['as' => 'vendors.update', 'uses' => 'VendorsController@update']);
Route::delete('/vendors/{vendor}', ['as' => 'vendors.destroy', 'uses' => 'VendorsController@destroy']);

Route::get('/import', ['as' => 'import.index', 'uses' => 'ImportController@index']);
Route::post('/import', ['as' => 'import.process', 'uses' => 'ImportController@import']);

Route::post('/export', ['as' => 'export.process', 'uses' => 'ImportController@export']);
Route::get('/export/worksheet/costs', ['as' => 'export.worksheet.costs', 'uses' => 'ImportController@exportCostsWorksheet']);
Route::get('/export/worksheet/sales', ['as' => 'export.worksheet.sales', 'uses' => 'ImportController@exportSalesWorksheet']);
Route::get('/export/worksheet/defaults', ['as' => 'export.worksheet.defaults', 'uses' => 'ImportController@exportDefaultPrices']);

Route::get('/freight', ['as' => 'freight.index', 'uses' => 'FreightController@index']);
Route::post('/freight', ['as' => 'freight.process', 'uses' => 'FreightController@process']);

Route::get('/vendorprices/create/{product}', ['as' => 'vendorprices.create', 'uses' => 'VendorPricesController@create']);
Route::delete('/vendorprices/{vendorPrice}', ['as' => 'vendorprices.delete', 'uses' => 'VendorPricesController@destroy']);

Route::get('/samples', ['as' => 'samples.index', 'uses' => 'SamplePackRequestController@index']);
Route::get('/samples/archive', ['as' => 'samples.archive', 'uses' => 'SamplePackRequestController@archive']);
Route::get('/samples/{sample}', ['as' => 'samples.show', 'uses' => 'SamplePackRequestController@show']);
Route::post('/samples', ['as' => 'samples.store', 'uses' => 'SamplePackRequestController@store']);
Route::put('/samples/{sample}', ['as' => 'samples.update', 'uses' => 'SamplePackRequestController@update']);
Route::delete('/samples/{sample}', ['as' => 'samples.destroy', 'uses' => 'SamplePackRequestController@destroy']);

Route::get('/settings/edit', ['as' => 'settings.edit', 'uses' => 'SettingsController@edit']);
Route::put('/settings', ['as' => 'settings.update', 'uses' => 'SettingsController@update']);
Route::delete('/settings/{setting}', ['as' => 'settings.destroy', 'uses' => 'SettingsController@destroy']);

Route::get('/orders', ['as' => 'orders.create', 'uses' => 'OrdersController@create']);
Route::post('/orders', ['as' => 'orders.store', 'uses' => 'OrdersController@store']);

/*
    Data
 */
Route::group(['prefix' => 'data'], function() {
    Route::match(['GET', 'HEAD'], 'accounts/{account}/download', ['as' => 'accounts.download', 'uses' => 'Data\AccountsController@download']);
    Route::match(['GET', 'HEAD'], 'accounts/test', ['as' => 'accounts.test', 'uses' => 'Data\AccountsController@test']);

    Route::post('accounts', ['as' => 'accounts.store', 'uses' => 'Data\AccountsController@store']);
    Route::match(['GET', 'HEAD'], 'accounts', ['as' => 'accounts.index', 'uses' => 'Data\AccountsController@index']);
    Route::match(['GET', 'HEAD'], 'accounts/create', ['as' => 'accounts.create', 'uses' => 'Data\AccountsController@create']);
    Route::delete('accounts/{account}', ['as' => 'accounts.destroy', 'uses' => 'Data\AccountsController@destroy']);
    Route::match(['GET', 'HEAD'], 'accounts/{account}/restore', ['as' => 'accounts.restore', 'uses' => 'Data\AccountsController@restore']);
    Route::match(['PUT', 'PATCH'], 'accounts/{account}/update', ['as' => 'accounts.update', 'uses' => 'Data\AccountsController@update']);
    Route::match(['GET', 'HEAD'], 'accounts/{account}', ['as' => 'accounts.show', 'uses' => 'Data\AccountsController@show']);
    Route::match(['GET', 'HEAD'], 'accounts/{account}/edit', ['as' => 'accounts.edit', 'uses' => 'Data\AccountsController@edit']);

    Route::match(['GET', 'HEAD'], 'entries/{entry}/download', ['as' => 'entries.download', 'uses' => 'Data\EntriesController@download']);
    Route::post('entries', ['as' => 'entries.store', 'uses' => 'Data\EntriesController@store']);
    Route::delete('entries/{entry}', ['as' => 'entries.destroy', 'uses' => 'Data\EntriesController@destroy']);
    Route::match(['GET', 'HEAD'], 'entries/{entry}', ['as' => 'entries.show', 'uses' => 'Data\EntriesController@show']);
});

Route::get('guide', function() {
    return view('pages.guide');
});

Route::get('inventory-request', function () {
    return view('pages.inventory-request');
})->name('inventory-request');

use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;
