### ISSUE TITLE
No translate file fo LangFileManager

### ISSUE THREAD

**Issue by shbov** [Laravel-Backpack/langfilemanager#78]
![image](https://user-images.githubusercontent.com/32542672/72671007-620ef500-3a55-11ea-917c-fb4d799bbe9a.png)

**Comment by tabacitu** [comment]
Hi @shbov ,

Please include more details so we can help. What's the problem? From the screenshot it looks like you haven't properly installed LangFileManager - make sure you [follow all steps here](https://github.com/Laravel-Backpack/LangFileManager#install-in-laravel-6). You shouldn't be seeing ```Backpack::Langfilemanager.Translate``` as the title, but something prettier.

Hope it helps. Reopen if you can provide details, and properly installing the package doesn't help.
Cheers!
