### ISSUE TITLE
Laravel 9 compatiblity?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/langfilemanager#85]
@promatik you added Backpack v5 support in #82 , thank you 🙏

But did you think of Laravel 9 too? Does it include compatiblity with that? I'm asking that because in L9 the `lang` directory has been moved from `resources\lang` to `lang` (in root). See https://laravel.com/docs/9.x/upgrade#the-lang-directory 

We should be able to provide compatiblity for both, by using `app()->langPath()`

**Comment by tabacitu** [comment]
Ping @promatik ?

**Comment by promatik** [comment]
Fixed with #86.
